version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/tufin/totem
    steps:
      - checkout
      - run:
          name: Install the project's dependencies
          command:
            dep ensure -v
      - run:
          name: Test
          command:
            chmod +x /script/testcov.sh
            /script/testcov.sh
      - run:
          name: Upload coverage results
          command:
            bash <(curl -s https://codecov.io/bash)